version: "3.8"
services:
  sakugwej-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: sakugwej-backend:latest
    container_name: sakugwej-backend
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
