version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: saku-jwej-backend:latest
    container_name: saku-gwej-backend
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
